### ISSUE TITLE
Action Space Type

### ISSUE THREAD

**Issue by prajwalvinod** [Namasivaayam-L/pett_zoo#1]
Hey @Namasivaayam-L ,

I came across your profile while posting issues on the sumo-rl github page. I am currently working on my thesis in traffic management and I was hoping to get some insight from you since this is my first time exclusively coding RL in Python not mention using SUMO. I was hoping to run DDPG and SAC firstly directly from sb3 and then a hard coded version. While going through the documentation on sb3 I realized that the action space supported by SAC & DDPG is only Box whereas the action space definition in sumo-rl is discrete. How did you get around this issue when you ran the code for SAC and DDPG which you have in the test folder of your repository I believe. 

Hope you can enlighten me.

Thanks

**Comment by Namasivaayam-L** [comment]
Hey Hi.. I ran SAC. But I am not using SB3 anymore. I am just using my Own Model, that's it. As For DDPG, I met the same error as you. After that I moved on to use the custom model. So I am yet to create a custom model for DDPG. Happy to help with any other queries.

**Comment by prajwalvinod** [comment]
Hey @Namasivaayam-L ,

Thanks for your reply. I am also using the same approach of separately using SAC and DDPG agents. 

Regards

Prajwal

**Comment by Namasivaayam-L** [comment]
> Hey @Namasivaayam-L ,
> 
> Thanks for your reply. I am also using the same approach of separately using SAC and DDPG agents. 
> 
> Regards
> 
> Prajwal 

Ohh Okay.. If possible can you please share your repo for reference.
Thanks
